### ISSUE TITLE
RankedModel breaks rails console:  `NameError: uninitialized constant Product::RankedModel`

### ISSUE THREAD

**Issue by damassi** [mixonic/ranked-model#83]
Hey!  I'm running into a strange error after including RankedModel.  Everything within the app works perfectly, i'm able to resort and so on, but now my console no longer works when booting up `rails c`

My Product class looks like so:

```
class Release < ActiveRecord::Base
  include RankedModel
  ranks :row_order

  extend FriendlyId
  friendly_id :album, use: :slugged

  belongs_to  :artist, class_name: 'Artist', foreign_key: 'artist_id'
  has_many    :products
  has_many    :gallery_images
  accepts_nested_attributes_for :gallery_images

  mount_uploader :cover_photo, CoverPhotoUploader

  validates :album,   presence: true
  validates :catalog, presence: true
end
```

But when I boot up the console and try to execute any action on any model that is using RankedModel I receive an error:

```
irb(main):003:0> Product.all
NameError: uninitialized constant Product::RankedModel
    from /Users/damassi/Sites/UnseenWorlds/usw-backend/app/models/product.rb:3:in `<class:Product>'
    from /Users/damassi/Sites/UnseenWorlds/usw-backend/app/models/product.rb:1:in `<top (required)>'
    from (irb):3
    from /Users/damassi/.rvm/gems/ruby-2.1.0/gems/railties-4.1.4/lib/rails/commands/console.rb:90:in `start'
    from /Users/damassi/.rvm/gems/ruby-2.1.0/gems/railties-4.1.4/lib/rails/commands/console.rb:9:in `start'
    from /Users/damassi/.rvm/gems/ruby-2.1.0/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:69:in `console'
    from /Users/damassi/.rvm/gems/ruby-2.1.0/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
    from /Users/damassi/.rvm/gems/ruby-2.1.0/gems/railties-4.1.4/lib/rails/commands.rb:17:in `<top (required)>'
    from /Users/damassi/Sites/UnseenWorlds/usw-backend/bin/rails:8:in `<top (required)>'
    from /Users/damassi/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/damassi/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in `<main>'
```

Looking around on StackOverflow I can't seen to find any pointers, so I thought I would log this here.  Also, my project is very basic so I don't think there are any unknown interferences.  

Thanks!

**Comment by yoka** [comment]
+1 same issue with rails 4.1.5 (and using git repo in Gemfile does not seem to help)

**Comment by damassi** [comment]
@camilledelbos, not sure, this is what is in my Gem file, though I haven't updated app in a while!

`gem 'ranked-model', :git => 'https://github.com/mixonic/ranked-model.git'`

**Comment by Hainminsoe** [comment]
same here ! Rail (5.1)

**Comment by brendon** [comment]
Need more information than that I'm afraid :)

**Comment by MrMakintosh** [comment]
Restarting rails console helped me. Rails 5.0.2
